### ISSUE TITLE
[Doc] Same command twice in install documentation

### ISSUE THREAD

**Issue by SylvainDe** [Psycojoker/redbaron#92]
Hi,
I've just started to read the doc (after an email about the project was sent to the python code quality mailing list) and found an tiny issue on :
https://redbaron.readthedocs.org/en/latest/index.html
This part repeats the same command line:

pip install redbaron[pygments]
Or if you don’t want to have syntax highlight in your shell or don’t need it:
pip install redbaron[pygments]

Which I assume to be not correct. For the reference, the readme says:

pip install redbaron[pygments]
Or if you don't want to have syntax highlight in your shell or don't need it:
pip install redbaron

**Comment by Psycojoker** [comment]
Indeed, went a bit too fast on the doc (it's hard to test), thanks for reporting I've just fixed it :)

**Comment by SylvainDe** [comment]
Good job, thanks :)
(Also, the issue still seems to be here but I guess I have to wait for a bit)

**Comment by Psycojoker** [comment]
Yeah, the builds on readthedocs are actually failing, I've discovered that while trying to fix your other ticket but I can't find why he keeps try to install redbaron 0.6 instead of 0.6.1 :/

**Comment by SylvainDe** [comment]
Looks like it is fixed indeed now, thanks for fixing even small issues that quickly :+1:
